executor: cluster-generic
cluster-generic-submit-cmd:
  sbatch
    --partition={resources.partition}
    --mem={resources.mem_gb}G
    --cpus-per-task={resources.threads}
    --time={resources.time}
    --job-name=smk-{rule}-{wildcards}
    --output=logs/SLURM_out/{rule}/{rule}-%j-{wildcards}.out
    --mail-type=END,FAIL
    --mail-user={resources.mail}
    --parsable
default-resources:
  - mail="<YOUR-EMAIL-ADRESS>"
  - partition="small"
  - mem_gb=1
  - threads=10
  - time="00:30:00"
jobs: 500
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
keep-going: True
rerun-incomplete: True
restart-times: 3
printshellcmds: True
scheduler: greedy
cluster-generic-cancel-cmd: scancel
cluster-generic-cancel-nargs: 1000
cluster-generic-status-cmd: status-sacct.sh
